### ISSUE TITLE
error because not install sqlite database

### ISSUE THREAD

**Issue by youssriaboelseod** [ra-systems/django-ra-erp#11]
hi Ramiz
thank you for your grateful package 
we realy need your package and i will help you for improve it

after install ra-erp
i noticed that the website didn't load because the sqlite database hadn't generated

also there are problem in static_root

i will fix this on my web site because i am using PostgreSQL database but i attend you for this problem
youssri

**Comment by RamezIssac** [comment]
Good day ... Would share the error that appeared with you ?
I will revise on my end .

**Comment by youssriaboelseod** [comment]
python manage.py startapp first
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "E:\programing\websites\ra-erp\env\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "E:\programing\websites\ra-erp\env\lib\site-packages\django\core\management\__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "E:\programing\websites\ra-erp\env\lib\site-packages\django\conf\__init__.py", line 76, in __getattr__
    self._setup(name)
  File "E:\programing\websites\ra-erp\env\lib\site-packages\django\conf\__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "E:\programing\websites\ra-erp\env\lib\site-packages\django\conf\__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\ProgramData\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\programing\websites\ra-erp\aeraeg\aeraeg\settings.py", line 144
    STATIC_ROOT = os.path.join(BASE_DIR, '..', 'collected_static')
              ^
SyntaxError: invalid syntax

**Comment by youssriaboelseod** [comment]
no problem 
i am not creating new project i just i am integrating django-ra-erp on my project ,
